language: php

php:
    - 5.5
    - 5.6
    - hhvm
    - hhvm-nightly

matrix:
    allow_failures:
        - php: hhvm
        - php: hhvm-nightly

before_script:
    - composer install

script: phpunit -v
