language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - hhvm
    - hhvm-nightly

matrix:
    allow_failures:
        - php: hhvm
        - php: hhvm-nightly

before_script:
    - composer install

script: phpunit -v --coverage-clover coverage.clover

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
